from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ============================================================
# 1. CHANGE INFORMATION
# ============================================================

@dataclass
class ChangeInfo:
    """
    Describes what changed between two Git commits.
    """

    changed_files: List[str] = field(default_factory=list)
    changed_functions: List[str] = field(default_factory=list)
    diff: str = ""
    base_commit: Optional[str] = None
    target_commit: Optional[str] = None


# ============================================================
# 2. DEPENDENCY EVIDENCE
# ============================================================

@dataclass
class DependencyEvidence:
    """
    Represents one evidence-backed dependency relationship.

    Example:
        checkout.calculate_total
            -> pricing.final_price
    """

    source: str
    target: str
    edge_type: str

    file: Optional[str] = None
    line: Optional[int] = None

    evidence: str = ""

    confidence: float = 1.0


# ============================================================
# 3. IMPACT RESULT
# ============================================================

@dataclass
class ImpactResult:
    """
    Describes the components potentially affected by a change.
    """

    changed: List[str] = field(default_factory=list)

    direct: List[str] = field(default_factory=list)

    indirect: List[str] = field(default_factory=list)

    paths: List[List[str]] = field(default_factory=list)

    evidence: List[DependencyEvidence] = field(default_factory=list)

    uncertainty: List[str] = field(default_factory=list)


# ============================================================
# 4. TEST CANDIDATE
# ============================================================

@dataclass
class TestCandidate:
    """
    Represents a test that CodeImpact recommends running.
    """

    test_name: str
    test_file: str

    target_components: List[str] = field(default_factory=list)

    reason: str = ""

    confidence: float = 1.0


# ============================================================
# 5. TEST RESULT
# ============================================================

@dataclass
class TestResult:
    """
    Represents the result of executing one test.
    """

    test_name: str

    status: str
    # Expected values:
    # "passed"
    # "failed"
    # "error"
    # "skipped"

    duration: float = 0.0

    stdout: str = ""
    stderr: str = ""

    exit_code: Optional[int] = None


# ============================================================
# 6. EVALUATION RESULT
# ============================================================

@dataclass
class EvaluationResult:
    """
    Compares CodeImpact's prediction with observed test results.
    """

    predicted_components: List[str] = field(default_factory=list)

    actual_affected_components: List[str] = field(default_factory=list)

    true_positives: List[str] = field(default_factory=list)

    false_positives: List[str] = field(default_factory=list)

    false_negatives: List[str] = field(default_factory=list)

    precision: Optional[float] = None

    recall: Optional[float] = None

    total_tests: int = 0

    targeted_tests: int = 0

    test_reduction: Optional[float] = None


# ============================================================
# 7. AI EXPLANATION
# ============================================================

@dataclass
class AIExplanation:
    """
    Contains the explanation generated by the AI layer.

    The AI should explain repository evidence rather than
    inventing dependency relationships.
    """

    summary: str = ""

    reasoning: List[str] = field(default_factory=list)

    affected_components: List[str] = field(default_factory=list)

    test_reasoning: List[str] = field(default_factory=list)

    failure_summary: List[str] = field(default_factory=list)

    uncertainty: List[str] = field(default_factory=list)


# ============================================================
# 8. IMPACT REPORT
# ============================================================

@dataclass
class ImpactReport:
    """
    Complete result produced by CodeImpact.
    """

    change: Optional[ChangeInfo] = None

    impact: Optional[ImpactResult] = None

    recommended_tests: List[TestCandidate] = field(default_factory=list)

    test_results: List[TestResult] = field(default_factory=list)

    evaluation: Optional[EvaluationResult] = None

    ai_explanation: Optional[AIExplanation] = None

    generated_at: Optional[str] = None

    success: bool = True

    errors: List[str] = field(default_factory=list)